# golangci-lint v2.6.2 config
version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - bodyclose
    - unconvert
    - unparam
    - misspell
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gosec:
    excludes:
      - G404  # Weak random number generator (ok for non-crypto use)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - gochecknoinits
  
  max-issues-per-linter: 0
  max-same-issues: 0
